name: Test jPipe Runner

concurrency:
  group: runner-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  jpipe-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use jpipe-runner
        uses: ./
        with:
          jd_file: "examples/01_slides.jd"
          variable: |
            key:value
          library:
          dry_run: true
